41 implement overloaded jds constructor
bkochuna/ners570f22-SpMV pull request #66
Opened 2022-11-06 21:52 UTC by tcoonsUM

After review, this will add an overloaded JDS constructor and a test for the alternate declaration of a JDS matrix.

2022-11-06 22:52 UTC, A-CGray requested changes

2022-11-06 22:52 UTC, A-CGray commented on tests/test_SparseMatrix_JDS.cpp
> +  ASSERT_EQUAL(matrix.getState(), SpMV::building);
Could you add a test in here that checks that the values in the matrix are represented correctly? One example I can think of is to a series of MatVecs with vectors that have a 1 in the nth entry (e.g [0 1 0 0 0 0]) and check that the resulting vector is the nth column of the original matrix

2022-11-06 22:52 UTC, A-CGray commented on src/SparseMatrix_JDS.hpp
> +        this->_state = initialized;
I think this is done already when you call the parent class constructor

2022-11-06 22:52 UTC, A-CGray commented on src/SparseMatrix_JDS.hpp
> +      SparseMatrix_JDS(const size_t nrows, const size_t ncols, perm[], jdiag[], col_ind[], jd_ptr[]) : SparseMatrix<fp_type>::SparseMatrix(nrows, ncols) {
Can you put this method implementation outside of the class declaration, like the rest of them

2022-11-06 22:52 UTC, A-CGray commented on src/SparseMatrix_JDS.hpp
> +        this->_ncols = ncols;
As per my comment above, this is already done by the parent class constructor

2022-11-06 22:52 UTC, A-CGray commented on src/SparseMatrix_JDS.hpp
> +      SparseMatrix_JDS(const size_t nrows, const size_t ncols, perm[], jdiag[], col_ind[], jd_ptr[]) : SparseMatrix<fp_type>::SparseMatrix(nrows, ncols) {
All the input parameters need their types defined, you can find them on line 121

2022-11-06 22:52 UTC, A-CGray commented on src/SparseMatrix_JDS.hpp
> +      SparseMatrix_JDS(const size_t nrows, const size_t ncols) : SparseMatrix<fp_type>::SparseMatrix(nrows, ncols, perm[], jdiag[], col_ind[], jd_ptr[], val[]) {
What does this constructor do? There is no constructor in the parent class that takes these inputs. I think the constructor you have above and below this one are the only ones we need

2022-11-07 03:09 UTC, A-CGray commented on src/SparseMatrix_JDS.hpp
> +  SparseMatrix_JDS<fp_type>::SparseMatrix_JDS(const size_t nrows, const size_t ncols, size_t perm[], size_t jdiag[], int col_ind[], fp_type jd_ptr[]) : SparseMatrix<fp_type>::SparseMatrix(nrows, ncol
`_rowPerm` is a `std::vector` of `size_t`'s not an array, we could either change the input type or keep it the same and convert it to a vector inside the constructor

2022-11-07 03:12 UTC, A-CGray commented on src/SparseMatrix_JDS.hpp
> +        assert(this->_state == building);
Shouldn't this be `assembled`? since this constructor is populating the JDS data structures and not the `_buildCoeff` map. Also, the `_maxRowSize` attribute needs to be set

2022-11-07 21:10 UTC, tcoonsUM commented on src/SparseMatrix_JDS.hpp
> +        assert(this->_state == building);
@A-CGray I think you are right on the state. For _maxRowSize, is there an intuitive way to compute that? I will admit to not having done the JDS homework extra credit so it is pretty confusing to me (is _maxRowSize the max # of nonzeros per row?)

2022-11-07 21:17 UTC, A-CGray commented on src/SparseMatrix_JDS.hpp
> +        assert(this->_state == building);
hmmm, it's kinda tricky, I now that the length of the `_jdPtrs` array is `_maxRowSize + 1` but you wont be able to find that length if `_jdPtrs` is a standard array, so maybe the max row size also needs to be passed in as an input?

2022-11-07 21:18 UTC, tcoonsUM commented on src/SparseMatrix_JDS.hpp
> +        assert(this->_state == building);
I like the way you think. If the user knows their matrix, they should know their max row size (hopefully)

2022-11-07 21:21 UTC, A-CGray commented on src/SparseMatrix_JDS.hpp
> +        assert(this->_state == building);
Along the same lines, I think this function needs to set the value of `_nnz` too right? I think the last entry of `_jdPtrs` should always be the correct `_nnz` value, but accessing that also relies on knowing how long `_jdPtrs` is

2022-11-07 21:28 UTC, A-CGray commented on src/SparseMatrix_JDS.hpp
> +        vector<size_t> vecPerm(perm,perm+sizeof(perm)/sizeof(perm[0]));
This is super nitpicky because what you have will work too, but perm should always be `nrows` long and it's a bit more readable to just write `vecPerm(perm, nrows);`

2022-11-07 21:29 UTC, tcoonsUM commented on src/SparseMatrix_JDS.hpp
> +        vector<size_t> vecPerm(perm,perm+sizeof(perm)/sizeof(perm[0]));
Nitpick away, your help is really appreciated

2022-11-07 21:51 UTC, A-CGray approved these changes

2022-11-07 21:51 UTC, A-CGray commented on src/SparseMatrix_JDS.hpp
> +      SparseMatrix_JDS(const size_t nrows, const size_t ncols, size_t perm[], size_t jdiag[], int col_ind[], fp_type jd_ptr[], size_t max_row_size) : SparseMatrix<fp_type>::SparseMatrix(nrows, ncols)
Looks good! just one last thing, `jd_ptrs` is the array of jagged diagonal pointers (equivalent to the `_jdPtrs` attribute), and `jdiag` is the array of the actual matrix values (equivalent to the `_values` attribute)

2022-11-07 21:57 UTC, A-CGray commented
Thanks for making all these changes @tcoonsUM , once you make that last change can you resolve the merge conflicts? Then I'm happy to merge this into the JDS branch and we can see if everything works together

2022-11-08 01:13 UTC, A-CGray commented on src/SparseMatrix_JDS.hpp
> +      SparseMatrix_JDS(const size_t nrows, const size_t ncols, size_t perm[], size_t jdiag[], int col_ind[], fp_type jd_ptr[], size_t max_row_size) : SparseMatrix<fp_type>::SparseMatrix(nrows, ncols)
I think the types of the variables in the function definition and body need to be updated too

2022-11-08 01:28 UTC, merged